matrix:
  include:
    - language: java
      jdk: openjdk11
      install: true
      script:
        - "mvn test"
    - language: node_js
      node_js: 10
      before_install:
        - cd react
      install: "npm install"
      script:
        - "npm test"
notifications:
  email: false